#!/usr/bin/env python3

# .SHELLDOC
#
# BitShuffle command-line client. Supports encoding & decoding.
#
# .ENDOC

import os
import sys
import argparse
import base64
import bz2

stderr = sys.stderr
stdout = sys.stdout
stdin = sys.stdin

def main():
    have_term = stdin.isatty()

    parser = argparse.ArgumentParser(description="")

    parser.add_argument("--input", "-i", default="/dev/stdin",
                            help="Input file. Default is stdin")
    parser.add_argument("--output", "-o", default="/dev/stdout")


    iochoice = parser.add_mutually_exclusive_group(required=True)

    iochoice.add_argument("--encode", "-e", action="store_true",
                            help="Generate a BitShuffle data packet from " +
                            "the input file")

    iochoice.add_argument("--decode", "-d", "-D", action="store_true",
                            help="Extract a BitShuffle data packet.")

    args = parser.parse_args()

    


if __name__ == "__main__":
	main()
